export type { CustomerServiceAgent } from '@/admin/objects/CustomerServiceAgent'
export type { OperationsManager } from '@/admin/objects/OperationsManager'
export type { MerchantApplication } from '@/admin/objects/MerchantApplication'
export type { ComplaintTicket } from '@/admin/objects/ComplaintTicket'
export type { PromotionCampaign } from '@/admin/objects/PromotionCampaign'
