package delivery.order.objects

import delivery.shared.objects.{MerchantId, OrderId, OrderStatus, Promotion, RefundStatus, RiderId, UserId, Voucher}

final case class Order(
    id: OrderId,
    customerId: UserId,
    customerName: String,
    customerPhone: String,
    merchantId: MerchantId,
    riderId: Option[RiderId],
    items: List[OrderItem],
    totalAmount: Double,
    deliveryAddress: String,
    status: OrderStatus,
    placedAt: String,
    originalAmount: Double = 0,
    discountAmount: Double = 0,
    payableAmount: Double = 0,
    usedVoucher: Option[Voucher] = None,
    merchantDiscountAmount: Double = 0,
    platformDiscountAmount: Double = 0,
    merchantReceivableAmount: Double = 0,
    appliedPromotions: List[Promotion] = Nil,
    priceSnapshot: Option[OrderPriceSnapshot] = None,
    priceBreakdown: Option[OrderPriceBreakdown] = None,
    pointsAwarded: Int = 0,
    refundStatus: Option[RefundStatus] = None,
    refundReason: Option[String] = None,
    refundImageUrl: Option[String] = None,
    refundRequestedAt: Option[String] = None,
    refundMerchantReason: Option[String] = None,
    refundMerchantReviewedAt: Option[String] = None,
    refundAdminReason: Option[String] = None,
    refundedAt: Option[String] = None,
    customerNoteText: Option[String] = None,
    customerNoteImageUrl: Option[String] = None,
    statusTimeline: List[OrderTimelineEvent] = Nil,
    estimatedPrepMinutes: Option[Int] = None,
    estimatedReadyAt: Option[String] = None,
    prepDelayReason: Option[String] = None,
    prepDelayedAt: Option[String] = None,
    prepTimeoutNotifiedAt: Option[String] = None
)
